### PR TITLE
More verbose test file

### PR DESCRIPTION
**Pull request by JessiFischer**

### CODE REVIEW

**Comment by nstielau** [comment]
How is this different than https://github.com/pantheon-systems/soip-example/blob/master/index.php?

**Comment by nstielau** [comment]
Or, actually closer to this one: https://github.com/pantheon-systems/soip-example/blob/master/example_remote_http.php

**Comment by JessiFischer** [comment]
There are a couple more lines in there verifying, though I'm failing to remember why these lines are important to have for verifying to remote server hit. @garydylina wrote this out and I'm just making a pass to merge it in. Here are the relevant/important added lines.

curl_setopt($ch, CURLOPT_RESOLVE, $resolve_host);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);

**Comment by nstielau** [comment]
Thanks.  Closing in favor of #5

**Pull request closed without merging**
